version: "3.9"

services:
  web:
    image: 127.0.0.1:5000/linux-project3-iac_web
    build: ./app
    ports:
      - "8000:8000"
  redis:
    image: redis:alpine
  nginx:
    image: 127.0.0.1:5000/linux-project3-iac_nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
